#!/usr/bin/env python3
"""Generate the two appendices that must not be typed by hand.

  parts/D_coverage.tex   blueprint topic -> chapter, from Cisco's PDF and
                         the \\bp{} tags in parts/*.tex
  (lab index)            chapter -> lab number, title and platform, printed
                         to stdout as LaTeX for pasting into G_schedule.tex

Both are derived from the source, so they cannot drift from it. Re-run after
adding or moving a chapter:

    python tools/gen_appendices.py

check_coverage.py verifies the same mapping and is the gate; this script
formats it.
"""
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PARTS = os.path.join(ROOT, "parts")
MASTER = os.path.join(ROOT, "CCNA_v2_Handout.tex")

sys.path.insert(0, HERE)
from check_coverage import read_blueprint  # noqa: E402


def chapter_order():
    """Chapter number for each parts/ file, in the order the master inputs them."""
    text = io.open(MASTER, encoding="utf-8").read()
    order, n = {}, 0
    for stem in re.findall(r"\\input\{parts/([^}]+)\}", text):
        path = os.path.join(PARTS, stem + ".tex")
        if not os.path.exists(path):
            continue
        body = io.open(path, encoding="utf-8").read()
        if re.search(r"^\\chapter\{", body, re.M):
            n += 1
            order[stem] = n
    return order


def scan():
    """Return {stem: {'num','title','topics','labs'}} for every chapter."""
    order = chapter_order()
    out = {}
    for stem, num in order.items():
        body = io.open(os.path.join(PARTS, stem + ".tex"), encoding="utf-8").read()
        title = re.search(r"\\chapter\{(.+?)\}", body)
        topics = []
        for tag in re.findall(r"\\bp\{([^}]*)\}", body):
            topics += [t.strip() for t in tag.split(",") if t.strip()]
        labs = re.findall(r"\\begin\{lab\}\{(.+?)\}\{(.+?)\}", body)
        out[stem] = {
            "num": num,
            "title": title.group(1) if title else stem,
            "topics": topics,
            "labs": labs,
        }
    return out


DOMAIN_COLOUR = {"1": "dom1", "2": "dom2", "3": "dom3", "4": "dom4", "5": "dom5"}


def tex_escape(s):
    """Escape the characters Cisco's wording actually contains."""
    return (s.replace("\\", "")
             .replace("&", "\\&")
             .replace("%", "\\%")
             .replace("_", "\\_")
             .replace("#", "\\#"))


def write_coverage(chapters):
    domains, topics = read_blueprint()

    by_topic = {}
    for info in chapters.values():
        for t in info["topics"]:
            by_topic.setdefault(t, []).append(info["num"])

    L = []
    add = L.append
    add("% GENERATED by tools/gen_appendices.py -- do not edit by hand.")
    add("% Re-run that script after adding, moving or retagging a chapter.")
    add("\\chapter{Blueprint Coverage Matrix}\\label{app:coverage}")
    add("")
    add("Every topic in Cisco's published exam-topics document for CCNA 200-301")
    add("version~2.0, and the chapter of this volume that teaches it. The table is")
    add("generated from the \\cmd{\\textbackslash bp\\{\\}} tags in the chapter")
    add("sources and from the PDF itself, so it cannot drift from either.")
    add("")
    add("\\begin{longtable}{@{}L{1.3cm}L{9.9cm}L{3.3cm}@{}}")
    add("\\toprule")
    add("\\rowcolor{primary!15}")
    add("\\textbf{Topic} & \\textbf{Cisco's wording} & \\textbf{Chapter} \\\\")
    add("\\midrule")
    add("\\endhead")

    shade = False
    last_domain = None
    for t in sorted(topics, key=lambda s: (int(s.split(".")[0]), int(s.split(".")[1]))):
        d = t.split(".")[0]
        if d != last_domain:
            weight, name = domains.get(d, ("", ""))
            add("\\midrule")
            # The weight is "25%" and must be escaped too -- a raw % here
            # comments out the rest of the row.
            add("\\multicolumn{3}{@{}l}{\\textcolor{%s!45!black}{\\textbf{Domain %s.0"
                " --- %s\\quad %s}}} \\\\" % (DOMAIN_COLOUR[d], d,
                                              tex_escape(name),
                                              tex_escape(weight)))
            add("\\midrule")
            last_domain = d
            shade = False
        if shade:
            add("\\rowcolor{lightbg}")
        shade = not shade
        nums = sorted(set(by_topic.get(t, [])))
        where = ", ".join(str(n) for n in nums) if nums else "\\textbf{--}"
        add("\\tp{%s} & %s & %s \\\\" % (t, tex_escape(topics[t]), where))

    add("\\bottomrule")
    add("\\end{longtable}")
    add("")

    path = os.path.join(PARTS, "D_coverage.tex")
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("wrote %s  (%d topics)" % (path, len(topics)))


def print_lab_index(chapters):
    print("\n% ---- lab index, paste into G_schedule.tex ----")
    print("\\begin{longtable}{@{}L{1.6cm}L{8.6cm}L{4.5cm}@{}}")
    print("\\toprule")
    print("\\rowcolor{primary!15}")
    print("\\textbf{Lab} & \\textbf{Title} & \\textbf{Platform} \\\\")
    print("\\midrule")
    print("\\endhead")
    shade = False
    total = 0
    for stem in sorted(chapters, key=lambda s: chapters[s]["num"]):
        info = chapters[stem]
        for i, (title, platform) in enumerate(info["labs"], start=1):
            if shade:
                print("\\rowcolor{lightbg}")
            shade = not shade
            print("%d.%d & %s & %s \\\\" % (info["num"], i, title, platform))
            total += 1
    print("\\bottomrule")
    print("\\end{longtable}")
    withlabs = sum(1 for c in chapters.values() if c["labs"])
    print("%% %d labs; %d of %d chapters carry one"
          % (total, withlabs, len(chapters)))
    for stem in sorted(chapters, key=lambda s: chapters[s]["num"]):
        if not chapters[stem]["labs"] and chapters[stem]["num"] <= 34:
            print("%%   no lab: ch %d %s"
                  % (chapters[stem]["num"], chapters[stem]["title"]))


if __name__ == "__main__":
    ch = scan()
    write_coverage(ch)
    print_lab_index(ch)
